// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_weighted_mean
double cpp_weighted_mean(NumericVector x, NumericVector w);
RcppExport SEXP _TwoWayFEWeights_cpp_weighted_mean(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_weighted_mean(x, w));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rev_cumsum_by_group
NumericVector cpp_rev_cumsum_by_group(IntegerVector g, NumericVector x);
RcppExport SEXP _TwoWayFEWeights_cpp_rev_cumsum_by_group(SEXP gSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rev_cumsum_by_group(g, x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fdtr_wtilde2
NumericVector cpp_fdtr_wtilde2(IntegerVector g, NumericVector t, NumericVector eps_2, NumericVector P_gt);
RcppExport SEXP _TwoWayFEWeights_cpp_fdtr_wtilde2(SEXP gSEXP, SEXP tSEXP, SEXP eps_2SEXP, SEXP P_gtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eps_2(eps_2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type P_gt(P_gtSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fdtr_wtilde2(g, t, eps_2, P_gt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_feS_delta
List cpp_feS_delta(IntegerVector g, NumericVector t, NumericVector D, NumericVector P_gt);
RcppExport SEXP _TwoWayFEWeights_cpp_feS_delta(SEXP gSEXP, SEXP tSEXP, SEXP DSEXP, SEXP P_gtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type P_gt(P_gtSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_feS_delta(g, t, D, P_gt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TwoWayFEWeights_cpp_weighted_mean", (DL_FUNC) &_TwoWayFEWeights_cpp_weighted_mean, 2},
    {"_TwoWayFEWeights_cpp_rev_cumsum_by_group", (DL_FUNC) &_TwoWayFEWeights_cpp_rev_cumsum_by_group, 2},
    {"_TwoWayFEWeights_cpp_fdtr_wtilde2", (DL_FUNC) &_TwoWayFEWeights_cpp_fdtr_wtilde2, 4},
    {"_TwoWayFEWeights_cpp_feS_delta", (DL_FUNC) &_TwoWayFEWeights_cpp_feS_delta, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_TwoWayFEWeights(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
