# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_weighted_mean <- function(x, w) {
    .Call(`_TwoWayFEWeights_cpp_weighted_mean`, x, w)
}

cpp_rev_cumsum_by_group <- function(g, x) {
    .Call(`_TwoWayFEWeights_cpp_rev_cumsum_by_group`, g, x)
}

cpp_fdtr_wtilde2 <- function(g, t, eps_2, P_gt) {
    .Call(`_TwoWayFEWeights_cpp_fdtr_wtilde2`, g, t, eps_2, P_gt)
}

cpp_feS_delta <- function(g, t, D, P_gt) {
    .Call(`_TwoWayFEWeights_cpp_feS_delta`, g, t, D, P_gt)
}

